dist: xenial # needed to use python 3.7
language: python
python:
  - "3.7.4"

cache: pip

branches:
  only:
    - master

addons:
  apt:
    packages:
      - pandoc
install:
#  - pip install pandoc==2.2.3
  - pip install Sphinx==1.8.5     # too recent version breaks links to exercises
  - pip install nbsphinx==0.4.2
  - pip install ipykernel
  - pip install sphinx_press_theme
  - pip install sphinx_rtd_theme
  - pip install lxml
  - pip install beautifulsoup4
  - pip install numpy==1.17.3
  - pip install pandas==0.25.1
  - pip install matplotlib==3.1.1
  - pip install scikit-learn==0.21.3
  - pip install scipy==1.3.1
  - pip install seaborn==0.9.0

script:
  # Use Sphinx to make the html docs
  - make html
  # Tell GitHub not to use jekyll to compile the docs
  - touch _build/html/.nojekyll

# Tell Travis CI to copy the documentation to the gh-pages branch of
# your GitHub repository.
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  on:
    branch: master
  local_dir: _build/html/

notifications:
  email:
    recipients:
      - kbakaric1@gmail.com
    on_success: change
    on_failure: always
