dist: xenial # needed to use python 3.7
language: python
python:
  - "3.7.4"

cache: pip

branches:
  only:
    - master

addons:
  apt:
    packages:
      - pandoc
install:
#  - pip install pandoc==2.2.3
  - pip install Sphinx==1.8.5     # too recent version breaks links to exercises
  - pip install nbsphinx==0.4.2
  - pip install ipykernel
  - pip install sphinx_press_theme
  - pip install sphinx_rtd_theme
  - pip install lxml
  - pip install beautifulsoup4
  - pip install numpy==1.17.3
  - pip install pandas==0.25.1
  - pip install matplotlib==3.1.1
  - pip install scikit-learn==0.21.3
  - pip install scipy==1.3.1
  - pip install seaborn==0.9.0
  - go get github.com/errata-ai/vale # install vale

script:
  - skip # Travis requires a `script` property, but we do not need it
stages:
  - build and test
  - deploy

jobs:
  include:
    - stage: build and test # This stage builds and lints in parallel
      name: Build
      script: make html # build the docs
      skip-cleanup: true
    - script: vale source # run vale
      name: Test
    - stage: deploy
      name: Deploy to GitHub Pages
      if: (NOT type IN (pull_request)) AND (branch = master) # only deploy if merging on master
      script: make html
      deploy:
        provider: gh-pages # deploy on github pages
        skip_cleanup: true
        github_token: $GITHUB_TOKEN # defined via the Travis interface
        local_dir: build/html

notifications:
  email:
    recipients:
      - kbakaric1@gmail.com
    on_success: change
    on_failure: always
